/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PromotionRouteImport } from './routes/promotion'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MarksRouteImport } from './routes/marks'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HostelRouteImport } from './routes/hostel'
import { Route as GradesRouteImport } from './routes/grades'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentStudentIdRouteImport } from './routes/student.$studentId'

const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionRoute = PromotionRouteImport.update({
  id: '/promotion',
  path: '/promotion',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MarksRoute = MarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelRoute = HostelRouteImport.update({
  id: '/hostel',
  path: '/hostel',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesRoute = GradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentStudentIdRoute = StudentStudentIdRouteImport.update({
  id: '/student/$studentId',
  path: '/student/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/classes': typeof ClassesRoute
  '/exams': typeof ExamsRoute
  '/fees': typeof FeesRoute
  '/grades': typeof GradesRoute
  '/hostel': typeof HostelRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/marks': typeof MarksRoute
  '/messages': typeof MessagesRoute
  '/promotion': typeof PromotionRoute
  '/ranking': typeof RankingRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/students': typeof StudentsRoute
  '/teachers': typeof TeachersRoute
  '/timetable': typeof TimetableRoute
  '/transport': typeof TransportRoute
  '/student/$studentId': typeof StudentStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/classes': typeof ClassesRoute
  '/exams': typeof ExamsRoute
  '/fees': typeof FeesRoute
  '/grades': typeof GradesRoute
  '/hostel': typeof HostelRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/marks': typeof MarksRoute
  '/messages': typeof MessagesRoute
  '/promotion': typeof PromotionRoute
  '/ranking': typeof RankingRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/students': typeof StudentsRoute
  '/teachers': typeof TeachersRoute
  '/timetable': typeof TimetableRoute
  '/transport': typeof TransportRoute
  '/student/$studentId': typeof StudentStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/classes': typeof ClassesRoute
  '/exams': typeof ExamsRoute
  '/fees': typeof FeesRoute
  '/grades': typeof GradesRoute
  '/hostel': typeof HostelRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/marks': typeof MarksRoute
  '/messages': typeof MessagesRoute
  '/promotion': typeof PromotionRoute
  '/ranking': typeof RankingRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/students': typeof StudentsRoute
  '/teachers': typeof TeachersRoute
  '/timetable': typeof TimetableRoute
  '/transport': typeof TransportRoute
  '/student/$studentId': typeof StudentStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/attendance'
    | '/classes'
    | '/exams'
    | '/fees'
    | '/grades'
    | '/hostel'
    | '/library'
    | '/login'
    | '/marks'
    | '/messages'
    | '/promotion'
    | '/ranking'
    | '/register'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/students'
    | '/teachers'
    | '/timetable'
    | '/transport'
    | '/student/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/attendance'
    | '/classes'
    | '/exams'
    | '/fees'
    | '/grades'
    | '/hostel'
    | '/library'
    | '/login'
    | '/marks'
    | '/messages'
    | '/promotion'
    | '/ranking'
    | '/register'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/students'
    | '/teachers'
    | '/timetable'
    | '/transport'
    | '/student/$studentId'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/attendance'
    | '/classes'
    | '/exams'
    | '/fees'
    | '/grades'
    | '/hostel'
    | '/library'
    | '/login'
    | '/marks'
    | '/messages'
    | '/promotion'
    | '/ranking'
    | '/register'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/students'
    | '/teachers'
    | '/timetable'
    | '/transport'
    | '/student/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AttendanceRoute: typeof AttendanceRoute
  ClassesRoute: typeof ClassesRoute
  ExamsRoute: typeof ExamsRoute
  FeesRoute: typeof FeesRoute
  GradesRoute: typeof GradesRoute
  HostelRoute: typeof HostelRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MarksRoute: typeof MarksRoute
  MessagesRoute: typeof MessagesRoute
  PromotionRoute: typeof PromotionRoute
  RankingRoute: typeof RankingRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  StudentsRoute: typeof StudentsRoute
  TeachersRoute: typeof TeachersRoute
  TimetableRoute: typeof TimetableRoute
  TransportRoute: typeof TransportRoute
  StudentStudentIdRoute: typeof StudentStudentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotion': {
      id: '/promotion'
      path: '/promotion'
      fullPath: '/promotion'
      preLoaderRoute: typeof PromotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marks': {
      id: '/marks'
      path: '/marks'
      fullPath: '/marks'
      preLoaderRoute: typeof MarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostel': {
      id: '/hostel'
      path: '/hostel'
      fullPath: '/hostel'
      preLoaderRoute: typeof HostelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades': {
      id: '/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof GradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/$studentId': {
      id: '/student/$studentId'
      path: '/student/$studentId'
      fullPath: '/student/$studentId'
      preLoaderRoute: typeof StudentStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AttendanceRoute: AttendanceRoute,
  ClassesRoute: ClassesRoute,
  ExamsRoute: ExamsRoute,
  FeesRoute: FeesRoute,
  GradesRoute: GradesRoute,
  HostelRoute: HostelRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MarksRoute: MarksRoute,
  MessagesRoute: MessagesRoute,
  PromotionRoute: PromotionRoute,
  RankingRoute: RankingRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  StudentsRoute: StudentsRoute,
  TeachersRoute: TeachersRoute,
  TimetableRoute: TimetableRoute,
  TransportRoute: TransportRoute,
  StudentStudentIdRoute: StudentStudentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
